// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD3CMrIaFsI7956yFpnp3BNQSHhJRtqDw',
    appId: '1:30440294168:web:88a141c89d7271df3ac06d',
    messagingSenderId: '30440294168',
    projectId: 'todo-app-9a29f',
    authDomain: 'todo-app-9a29f.firebaseapp.com',
    storageBucket: 'todo-app-9a29f.appspot.com',
    measurementId: 'G-WQ1FWE81P9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuNW5NwB3HIt-bZ-eOflDNldVw33CGEa8',
    appId: '1:30440294168:android:642d81968906df783ac06d',
    messagingSenderId: '30440294168',
    projectId: 'todo-app-9a29f',
    storageBucket: 'todo-app-9a29f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIxJdZJAVABFysCyIwhVhBfyLkaBfWO6k',
    appId: '1:30440294168:ios:7807a3273f3428283ac06d',
    messagingSenderId: '30440294168',
    projectId: 'todo-app-9a29f',
    storageBucket: 'todo-app-9a29f.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIxJdZJAVABFysCyIwhVhBfyLkaBfWO6k',
    appId: '1:30440294168:ios:7807a3273f3428283ac06d',
    messagingSenderId: '30440294168',
    projectId: 'todo-app-9a29f',
    storageBucket: 'todo-app-9a29f.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDD3CMrIaFsI7956yFpnp3BNQSHhJRtqDw',
    appId: '1:30440294168:web:335056a5000bb20b3ac06d',
    messagingSenderId: '30440294168',
    projectId: 'todo-app-9a29f',
    authDomain: 'todo-app-9a29f.firebaseapp.com',
    storageBucket: 'todo-app-9a29f.appspot.com',
    measurementId: 'G-QC0MKGT644',
  );
}
